### ISSUE TITLE
Allocator problem 

### ISSUE THREAD

**Issue by ForserX** [mtsamis/box2d-optimized#5]
![image](https://user-images.githubusercontent.com/13867290/192076675-00c77e55-d291-4e8a-afab-c756c1751181.png)

![image](https://user-images.githubusercontent.com/13867290/192076751-15019ead-1e76-450d-9dad-da236f53eb19.png)

Double free

**Comment by Vertver** [comment]
+1

**Comment by mtsamis** [comment]
Do you have a test case / example that can reproduce that?

**Comment by ForserX** [comment]
ForserX#6279

**Comment by Vertver** [comment]
This reproducing if you're trying to destroy more than 5-10 objects per step/tick. 

Destroy code:
```cpp
void
physics::physics_body::destroy()
{
	destroyed = true;
	for (auto joint = body->GetJointList(); joint != nullptr; ) {
		const auto next_joint = joint->next;
		get_world().DestroyJoint(joint->joint);
		joint = next_joint;
	}
	
	get_world().DestroyBody(body);
	body = nullptr;
}
```

pre_tick() code:
```
        for (const auto body : scheduled_to_delete_bodies) {
		body->destroy();
		if (bodies.contains(body)) {
			bodies.erase(body);
		}
	}
	
	scheduled_to_delete_bodies.clear();
```

My guess is that the crash is because `b2Contact` and `b2Fixture` which is stored inside `b2Body` have been already cleared in another object, but the pointers have not been nullptr'ed (they are just 0xFDFDFDFD).
![image](https://user-images.githubusercontent.com/27735427/192864626-b0b657e5-af80-4217-982e-70a58facac65.png)
![image](https://user-images.githubusercontent.com/27735427/192865079-46b696d1-9619-412d-b58a-635d99723b83.png)

**Comment by Vertver** [comment]
this issue was fixed by this code

```	stl::hash_set<b2Contact*> contacts;
	for (const auto body : scheduled_to_delete_bodies) {
		const auto phys_body = body->get_body();
		if (phys_body != nullptr) {
			// In this case, we're trying to write temp pointer to this element to
			// delete after searching this contact in all bodies.
			for (int i = 0; i < phys_body->GetContactCount(); i++) {
				const auto contact = phys_body->GetContact(i);
				if (contact != nullptr) {
					contacts.insert(contact);
				}
			}

			// Second - try to delete all referenced links in body
			phys_body->ClearContacts();

			// Third - delete all fixtures by self
			auto fixture = phys_body->GetFixtureList();
			while (fixture != nullptr) {
				const auto next_fixture = fixture->GetNext();
				phys_body->DestroyFixture(fixture);
				fixture = next_fixture;
			}
		}
	}

	// Yep, this is most interesting part: we're deleting all founded by iterating
	// contacts and free it after processing
	for	(const auto contact : contacts) {
		world_holder->GetContactManager().Destroy(contact);
	}```

**Comment by mtsamis** [comment]
Yes this makes some sense; after having a look at it I think that the way `b2World::RemoveDeadContacts` works is incorrect when combined with how contact destruction logic. I believe the condition `contact->m_flags & b2Contact::e_persistFlag` can also access free'd memory in that case.

Thanks for providing a workaround to the issue, I'll try to reproduce this and explore other solutions as well when I have some time.

**Comment by RonYanDaik** [comment]
> ```c++
> GetContactManager().Destroy
> ```

Where this code should be placed?

**Comment by ForserX** [comment]
Check this: 
https://github.com/ForserX/Asura2D/blob/master/src/engine/physics/physics_world.cpp
