### ISSUE TITLE
Crash after creating 28 dynamic objects at runtime.

### ISSUE THREAD

**Issue by RonYanDaik** [mtsamis/box2d-optimized#9]
For some reason after proceeding with Step function if i try  create new dynamic object and number of dynamic object is more then 28 I get crash at ContactManager::FindNewContacts.

I don't have such issue with original lib.
Am I suppose to suppose to set up something?
Thank you.

![image](https://user-images.githubusercontent.com/3350340/230417149-7bf025e0-496c-4e2e-860c-1c590198fae3.png)

![image](https://user-images.githubusercontent.com/3350340/230417333-111fafce-29d0-49ff-b91f-56b615995ef5.png)

inside b2BroadPhase::UpdateAndQuery(T* callback)
![image](https://user-images.githubusercontent.com/3350340/230417831-c65966f1-2ef7-41a3-a83b-a8bd5d4abb58.png)

**Comment by RonYanDaik** [comment]
Looks like temp b2TreeNode is not being set because this condition` if (b2TestOverlap(m_rootStatic->aabb, m_links[i]->aabb))` never returns true and therefore temp has some field uninitialized.

![image](https://user-images.githubusercontent.com/3350340/230489818-327e63c1-90a7-4ac1-88c0-e4ba195cff80.png)

**Comment by RonYanDaik** [comment]
I did some more testing and found out that the crash happens depending from number of static bodies in the  scene.

Crash happens:
![image](https://user-images.githubusercontent.com/3350340/230493940-983eb94a-e9e9-4aa8-ae40-f9a7dc141eba.png)

crash does not happen:
![image](https://user-images.githubusercontent.com/3350340/230494077-b182c982-22f6-442e-807b-94f2ad0fc3b0.png)

crash does not happen:
![image](https://user-images.githubusercontent.com/3350340/230494165-d83a9306-95c6-4af7-9133-88d278272490.png)

**Comment by RonYanDaik** [comment]
Apparently problem is here:

![image](https://user-images.githubusercontent.com/3350340/230496731-6feeca32-9d68-482c-b531-d323a8d2569a.png)

**m_rootStatic** members ore not valid (not null but also not a value). Thats why **(root->IsLeaf())** gives false

**Comment by mtsamis** [comment]
Hi, thanks for the detailed summary. In general the broadphase detector will use slightly different algorithms depending on the ratio of dynamic to static bodies because then it can do faster detection. This can be seen here https://github.com/mtsamis/box2d-optimized/blob/505bb43175e6126d13dba398c2cc5d618c818f89/include/box2d/b2_broad_phase.h#L278-L284
where the heuristic is enabled when the number of static bodies is > 1/8 of the total number of bodies. It looks like `m_rootStatic` is left invalid in one of the transitions of using the other broadphase strategy.

Do you have code that can help me reproduce that? I can have a look.

**Comment by RonYanDaik** [comment]
> Do you have code that can help me reproduce that?
I'm using it with godot game engine right now. So you would have to download it source and then I'll have to clean project so you'll be able to run it. Its kind of too many steps thing.

But you can try to tell me where to look and will tell what i see.

**Comment by RonYanDaik** [comment]
I've got new exception. this time it tries to access right member which is invalid.

![image](https://user-images.githubusercontent.com/3350340/230581661-43b0ad1b-e1dd-4ddb-afa9-bdbc8b26db30.png)

**Comment by RonYanDaik** [comment]
> Do you have code that can help me reproduce that? I can have a look.

I think I've managed to reproduce it in Tiles test.

this is the code for entire Tiles class. I've changed static ground creation and added creation of bodies in Step() function.

```
class Tiles : public Test
{
public:
    enum
    {
        e_count = 20
      };

    Tiles()
    {
        m_fixtureCount = 0;
        b2Timer timer;

        {
            float a = 10.5f;
            b2BodyDef bd;
            bd.position.y = -a;

            int32 N = 4;
            int32 M = 1;
            b2Vec2 position;
            position.y = 0.0f;
            for (int32 j = 0; j < M; ++j)
            {
                position.x = -N * a;
                for (int32 i = 0; i < N; ++i)
                {
                    b2Body* ground = m_world->CreateBody(&bd);

                    b2PolygonShape shape;
                    shape.SetAsBox(a, a);
                    ground->CreateFixture(&shape, 0.0f);
                    ++m_fixtureCount;
                    position.x += 2.0f * a;
                    ground->SetTransform(position,0.0f);
                }
                position.y -= 2.0f * a;
            }

        }

        {
            float a = 0.5f;
            b2PolygonShape shape;
            shape.SetAsBox(a, a);

            b2Vec2 x(-7.0f, 0.75f);
            b2Vec2 y;
            b2Vec2 deltaX(0.5625f, 1.25f);
            b2Vec2 deltaY(1.125f, 0.0f);

            for (int32 i = 0; i < e_count; ++i)
            {
                y = x;

                for (int32 j = i; j < e_count; ++j)
                {
                    b2BodyDef bd;
                    bd.type = b2_dynamicBody;
                    bd.position = y;
                    bd.position.y = 50 - bd.position.y;

                    b2Body* body = m_world->CreateBody(&bd);
                    body->CreateFixture(&shape, 5.0f);
                    ++m_fixtureCount;
                    y += deltaY;
                }

                x += deltaX;
            }
        }

        m_createTime = timer.GetMilliseconds();
    }

    void Step(Settings& settings) override
    {
        const b2ContactManager& cm = m_world->GetContactManager();
        int32 height = cm.m_broadPhase.GetTreeHeight();
        int32 leafCount = cm.m_broadPhase.GetCount();
        int32 minimumNodeCount = 2 * leafCount - 1;
        float minimumHeight = ceilf(logf(float(minimumNodeCount)) / logf(2.0f));
        g_debugDraw.DrawString(5, m_textLine, "dynamic tree height = %d, min = %d", height, int32(minimumHeight));
        m_textLine += m_textIncrement;

        Test::Step(settings);

        g_debugDraw.DrawString(5, m_textLine, "create time = %6.2f ms, fixture count = %d",
          m_createTime, m_fixtureCount);
        m_textLine += m_textIncrement;

        //b2DynamicTree* tree = &m_world->m_contactManager.m_broadPhase.m_tree;

        //if (m_stepCount == 400)
        //{
        //	tree->RebuildBottomUp();
        //}
        float a = 0.5f;
        b2PolygonShape shape;
        shape.SetAsBox(a, a);
        static int cnt =0;

        if(cnt<500)
        {
            cnt++;

            b2BodyDef bd;
            bd.type = b2_dynamicBody;
            bd.position.y = 50;

            b2Body* body = m_world->CreateBody(&bd);
            body->CreateFixture(&shape, 5.0f);
        }
    }

    static Test* Create()
    {
        return new Tiles;
    }

    int32 m_fixtureCount;
    float m_createTime;
};

static int testIndex = RegisterTest("Benchmark", "Tiles", Tiles::Create);

```

**Comment by RonYanDaik** [comment]
> I think I've managed to reproduce it in Tiles test.

Wait. No. Its something else. This gives exception in `int32 height = cm.m_broadPhase.GetTreeHeight();`

**Comment by RonYanDaik** [comment]
Please try the code above to reproduce the error.

**Comment by RonYanDaik** [comment]
I think this is also might be an issue.
m_treeAllocator  get assigned invalid value in `m_treeAllocator = m_nodes + m_capacity;` probably because `m_capacity` is bigger then allocated nodes in `m_nodes`.
![image](https://user-images.githubusercontent.com/3350340/230612800-9f0afa1c-506c-4967-8578-22c162f3bb67.png)

**Comment by RonYanDaik** [comment]
Maybe I'm onto something here?
Looks like `oldNodes` points to `m_rootStatic` and here its being freed with` b2Free(oldNodes)`.
And from here on `m_rootStatic` has invalid values.
![image](https://user-images.githubusercontent.com/3350340/230616059-7f634983-8a89-4ebf-a3f7-499a9da78dfd.png)

**Comment by RonYanDaik** [comment]
> And from here on `m_rootStatic` has invalid values.

Adding `m_rootStatic = nullptr;` there fixed the crash but I'm have no idea if it will break speed of algorithm.
